### PR TITLE
Add Intel solution brief to resources

### PR DESCRIPTION
**Pull request by woju**
Cc: @monavij

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow and @woju)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
We should probably just remove this?

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @woju)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should probably just remove this?
</blockquote></details>

+1
___
*[`templates/resources.html` line 153 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8zdagW99a9gJjcJtKF:-N8zdagW99a9gJjcJtKG:bg9fi0e) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d94c3a5af92c83bc9a7a1ea2b348fbc849b68ef9/templates/resources.html#L153)):*
> ```HTML
>                 </a>
>             </div>
>             <div class="document col-12 col-md-4 graphene-spacer-50 p-md-4">
> ```

@woju: Do we have a staging server/instance where you could host this change? Would be good if we had a simple way for reviewers to check if everything renders correctly for them.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Nope. This is relevant context of the change. We've discussed this already.
___
*[`templates/resources.html` line 153 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8zdagW99a9gJjcJtKF:-N90wVQF1iDtI0rY8ljk:b2huyeq) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d94c3a5af92c83bc9a7a1ea2b348fbc849b68ef9/templates/resources.html#L153)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju: Do we have a staging server/instance where you could host this change? Would be good if we had a simple way for reviewers to check if everything renders correctly for them.
</blockquote></details>

Not easily. You can checkout and build yourself (`sudo apt install lektor; lektor serve & firefox http://localhost:5000`, and I can add a full snippet to README, if the link currently there is not enough).

Best I can do would be to add this to jenkins and have it serve html artifacts, but that would require relative paths everywhere and I vaguely recall that has problems with `sitemap.xml`, though I don't remember the details.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
> We've discussed this already.

When/where?

This context is useless for anyone but maintainers who happen to already know more context (e.g. who Mona is, which is completely missing from here). IMO it's just confusing for the readers, at least in the current form.
___
*[`templates/resources.html` line 153 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8zdagW99a9gJjcJtKF:-N93w5Nf11FFVFY5lSWV:b-vo9413) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d94c3a5af92c83bc9a7a1ea2b348fbc849b68ef9/templates/resources.html#L153)):*
> and I can add a full snippet to README

Please do, although just mentioning the default port should already be enough.

> Best I can do would be to add this to jenkins and have it serve html artifacts

Seems to be an overkill, I think I'm ok with the current method.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We've discussed this already.

When/where?

This context is useless for anyone but maintainers who happen to already know more context (e.g. who Mona is, which is completely missing from here). IMO it's just confusing for the readers, at least in the current form.
</blockquote></details>

Can we proceed with this discussion?

I would suggest to change the commit body to:
```
Per request from Mona Vij from Intel, who co-authored this document.
```

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we proceed with this discussion?

I would suggest to change the commit body to:
```
Per request from Mona Vij from Intel, who co-authored this document.
```
</blockquote></details>

This is also ok. I.e. either Dmitrii's proposed version or just drop it altogether.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is also ok. I.e. either Dmitrii's proposed version or just drop it altogether.
</blockquote></details>

Pinging @woju just in case he missed the updates on this PR.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8TQVzj4ninV1Ve3Vpw):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Pinging @woju just in case he missed the updates on this PR.
</blockquote></details>

Done. Although this is already deployed, I guess I can change the commit message.
___
*[`templates/resources.html` line 153 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/5#-N8zdagW99a9gJjcJtKF:-NakOJ0P8DZW9pblwZ2Y:b-896fix) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d94c3a5af92c83bc9a7a1ea2b348fbc849b68ef9/templates/resources.html#L153)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> and I can add a full snippet to README

Please do, although just mentioning the default port should already be enough.

> Best I can do would be to add this to jenkins and have it serve html artifacts

Seems to be an overkill, I think I'm ok with the current method.
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
