### PR TITLE
NSF grant and new Intel logo

### PR DESCRIPTION
**Pull request by woju**
This is based off `woju/resources-202208`, which was already deployed. Plz merge that one (#5), then this PR.

image
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)

### CODE REVIEW

**Comment by woju** [comment]
Cc: @donporter

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`assets/static/img/1280px-Intel-logo.svg-1.png` line 0 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaR7Srm0KFKFqcvChxS:-NaR7Srm0KFKFqcvChxT:b9milp1) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d85418dd7e0f14adaeb45dd29f5bb7a76e4fc1b7/assets/static/img/1280px-Intel-logo.svg-1.png#L0)):*
What's the point of this file, if we always use `.svg` version?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`assets/static/img/1280px-Intel-logo.svg-1.png` line  at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaR7Srm0KFKFqcvChxS:-NaREcCE6TTXFDEWVoww:b-6tvnyp) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d85418dd7e0f14adaeb45dd29f5bb7a76e4fc1b7/assets/static/img/1280px-Intel-logo.svg-1.png#L)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this file, if we always use `.svg` version?
</blockquote></details>

This file is being deleted in this PR. Are you asking what's the point of deleting this file, if we don't use it anymore?

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`assets/static/img/1280px-Intel-logo.svg-1.png` line  at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaR7Srm0KFKFqcvChxS:-NaRHvAk5tBYZiLWWK4u:bhhknea) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d85418dd7e0f14adaeb45dd29f5bb7a76e4fc1b7/assets/static/img/1280px-Intel-logo.svg-1.png#L)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This file is being deleted in this PR. Are you asking what's the point of deleting this file, if we don't use it anymore?
</blockquote></details>

Oops, sorry, my bad. Reviewable doesn't say something like "deleted", so I didn't recognize it initially.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`assets/static/img/1280px-Intel-logo.svg-1.png` line  at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaR7Srm0KFKFqcvChxS:-NaRIfV7B9qJ_6v6WO8x:b53iw69) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/d85418dd7e0f14adaeb45dd29f5bb7a76e4fc1b7/assets/static/img/1280px-Intel-logo.svg-1.png#L)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, sorry, my bad. Reviewable doesn't say something like "deleted", so I didn't recognize it initially.
</blockquote></details>

Yeah, it just has red square or "File not in pull request at selected revision."

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

___
*[`assets/static/img/Intel_logo_2023-gray.svg` line 49 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaqcQv_5p6mBgg5o25K:-NaqcQva1MFJye5h0FMY:blrwoaa) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/2c202982f42834efe2a76f2feafb210f53675f71/assets/static/img/Intel_logo_2023-gray.svg#L49)):*
> ```SVG
>    id="style2">
> 	.st0{fill:#04C7FD;}
> 	.st1{fill:#0068B5;}
> ```

tabs here?
___
*[`templates/_footer.html` line 67 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaqbsCJ5TKnF0P_JzQR:-NaqbsCJ5TKnF0P_JzQS:b-nh3vqx) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/2c202982f42834efe2a76f2feafb210f53675f71/templates/_footer.html#L67)):*
> ```HTML
>         <div class="col-12">Supported by Fosshost</div>
> 
> 	<div class="col-12">&nbsp;</div>
> ```

tab -> space
___
*[`templates/_footer.html` line 77 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaqbtAy1tKaCLMIsk1y:-NaqbtAy1tKaCLMIsk1z:b-7ropln) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/2c202982f42834efe2a76f2feafb210f53675f71/templates/_footer.html#L77)):*
> ```HTML
>     </div>
> 
> 	<div class="col-12">&nbsp;</div>
> ```

ditto

**Review by donporter — DISMISSED** [review]
Thanks Woju!

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-:-Nb0kcMPE50aYakdAygA:b7ebr2k)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

___
*[`assets/static/img/Intel_logo_2023-gray.svg` line 49 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaqcQv_5p6mBgg5o25K:-NaqfFc-84atfl8O0i4d:bvnj9du) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/2c202982f42834efe2a76f2feafb210f53675f71/assets/static/img/Intel_logo_2023-gray.svg#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tabs here?
</blockquote></details>

This file was straight from Inkscape. It's wrong to edit it manually, it will be undone the second someone edits this file again.

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`assets/static/img/Intel_logo_2023-gray.svg` line 49 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaqcQv_5p6mBgg5o25K:-Nc8fMWuEM583kQ08Xxt:bwm40kv) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/2c202982f42834efe2a76f2feafb210f53675f71/assets/static/img/Intel_logo_2023-gray.svg#L49)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This file was straight from Inkscape. It's wrong to edit it manually, it will be undone the second someone edits this file again.
</blockquote></details>

Happy to revert, although it seems to render correctly in preview either way.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @donporter, and @mkow)

___
*[`assets/static/img/Intel_logo_2023-gray.svg` line 49 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/7#-NaqcQv_5p6mBgg5o25K:-Nc9vAIa51b-Ylo6oE7U:bdvxxot) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/2c202982f42834efe2a76f2feafb210f53675f71/assets/static/img/Intel_logo_2023-gray.svg#L49)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Happy to revert, although it seems to render correctly in preview either way.
</blockquote></details>

Yes, for rendering it doesn't matter at all.

**Review by kailun-qin — DISMISSED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

**Review by mkow — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @donporter)

**Review by donporter — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

**Review by woju — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
